apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ip-tracker.fullname" . }}-secret
type: Opaque
data:
  NOTION_TOKEN: {{ .Values.env.notionToken | b64enc | quote }}
  NOTION_PAGE_ID: {{ .Values.env.notionPageID | b64enc | quote }}

