#!/bin/bash
CONTAINER_NAME=ip_tracker

source .env

if [ -z "$IMAGE" ]; then
  echo "The IMAGE variable is not set. Use this to set the name/destination for the image. Exiting..."
  exit 1
fi

docker build \
  --cache-from=$IMAGE:latest \
   --output=type=registry,registry.insecure=true \
  -f ./Dockerfile \
  -t $IMAGE:latest \
  --push \
  .

